
var weatherCodeMap = new Map();
weatherCodeMap.set(4201, ["static/Images/Weather Symbols for Weather Codes/rain_heavy.svg", "Heavy Rain"]);
weatherCodeMap.set(4001, ["static/Images/Weather Symbols for Weather Codes/rain.svg", "Rain"]);
weatherCodeMap.set(4200, ["static/Images/Weather Symbols for Weather Codes/rain_light.svg", "Light Rain"]);
weatherCodeMap.set(6201, ["static/Images/Weather Symbols for Weather Codes/freezing_rain_heavy.svg", "Heavy Freezing Rain"]);
weatherCodeMap.set(6001, ["static/Images/Weather Symbols for Weather Codes/freezing_rain.svg", "Freezing Rain"]);
weatherCodeMap.set(6200, ["static/Images/Weather Symbols for Weather Codes/freezing_rain_light.svg", "Light Freezing Rain"]);
weatherCodeMap.set(6000, ["static/Images/Weather Symbols for Weather Codes/freezing_drizzle.svg", "Freezing Drizzle"]);
weatherCodeMap.set(4000, ["static/Images/Weather Symbols for Weather Codes/drizzle.svg", "Drizzle"]);
weatherCodeMap.set(7101, ["static/Images/Weather Symbols for Weather Codes/ice_pellets_heavy.svg", "Heavy Ice Pallets"]);
weatherCodeMap.set(7000, ["static/Images/Weather Symbols for Weather Codes/ice_pellets.svg", "Ice pallets"]);
weatherCodeMap.set(7102, ["static/Images/Weather Symbols for Weather Codes/ice_pellets_light.svg", "Light Ice Pallets"]);
weatherCodeMap.set(5101, ["static/Images/Weather Symbols for Weather Codes/snow_heavy.svg", "Heavy Snow"]);
weatherCodeMap.set(5000, ["static/Images/Weather Symbols for Weather Codes/snow.svg", "Snow"]);
weatherCodeMap.set(5100, ["static/Images/Weather Symbols for Weather Codes/snow_light.svg", "Light Snow"]);
weatherCodeMap.set(5001, ["static/Images/Weather Symbols for Weather Codes/flurries.svg", "Flurries"]);
weatherCodeMap.set(8000, ["static/Images/Weather Symbols for Weather Codes/tstorm.svg", "Thundersotrm"]);
weatherCodeMap.set(2100, ["static/Images/Weather Symbols for Weather Codes/fog_light.svg", "Light Fog"]);
weatherCodeMap.set(2000, ["static/Images/Weather Symbols for Weather Codes/fog.svg", "Fog"]);
weatherCodeMap.set(1001, ["static/Images/Weather Symbols for Weather Codes/cloudy.svg", "Cloudy"]);
weatherCodeMap.set(1102, ["static/Images/Weather Symbols for Weather Codes/mostly_cloudy.svg", "Mostly Cloudy"]);
weatherCodeMap.set(1101, ["static/Images/Weather Symbols for Weather Codes/partly_cloudy_day.svg", "Partly Cloudy"]);
weatherCodeMap.set(1100, ["static/Images/Weather Symbols for Weather Codes/mostly_clear_day.svg", "Mostly Clear"]);
weatherCodeMap.set(1000, ["static/Images/Weather Symbols for Weather Codes/clear_day.svg", "Clear, Sunny"]);
